[package]
name = "fontsan"
version = "0.1.0"
authors = ["The Servo Project Developers"]
description = "Sanitiser for untrusted font files"
build = "build.rs"
license = "BSD-3-Clause"

[dependencies]
libc = "*"

[dependencies.miniz-sys]
git = "https://github.com/alexcrichton/flate2-rs"

[build-dependencies]
gcc = "*"
