[package]
name = "fontsan"
version = "0.1.0"
authors = ["The Servo Project Developers"]
description = "Sanitiser for untrusted font files"
build = "build.rs"
license = "BSD-3-Clause"

[dependencies]
libc = "*"
miniz-sys = "*"

[target.'cfg(target_os = "android")'.dependencies]
servo-freetype-sys = "2.4.11"

[build-dependencies]
gcc = "*"
